In [5]:
import pandas as pd
import numpy as np
from tqdm import tqdm

tqdm.pandas()

import warnings
warnings.filterwarnings("ignore")

In [6]:
data = pd.read_csv('final_data_clusters.csv', index_col=0)
print(data.shape)
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'final_data_clusters.csv'

In [ ]:
users = list(data['user_id'].unique())
len(users)

In [ ]:
orders = list(data['order_id'].unique())
len(orders)

In [3]:
# data = data.set_index('user_id')
data = data.drop(columns='order_id')
data = data.drop_duplicates(subset=['user_id', 'order_number'])
cols = data.columns

NameError: name 'data' is not defined

In [4]:
data = data.sort_values(['user_id', 'order_number'])

NameError: name 'data' is not defined

In [7]:
print(data.shape)
data.head()

(594798, 515)

,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,1% Lowfat Milk,100 Calorie Per Bag Popcorn,100% Raw Coconut Water,100% Recycled Paper Towels,100% Whole Wheat Bread,...,Crackers Cheddar Bunnies Snack Packs,days_since_first_order,reorders,organics,basket_size,num_orders,global_reorders,tx_purpose_weekly,tx_purpose_monthly,clusters
63167,27,1,3,9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,83.0,0.0,0.0,0.0,2
289335,27,2,2,17,6.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.0,1.0,2.0,6.0,83.0,3.0,0.0,0.0,2
168422,27,3,3,8,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,7.0,1.0,0.0,2.0,83.0,2.0,0.0,0.0,2
495171,27,4,5,13,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,1.0,0.0,7.0,83.0,6.0,0.0,0.0,2
175636,27,5,2,15,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,17.0,2.0,0.0,2.0,83.0,1.0,0.0,0.0,2

In [8]:
indexed = data.set_index(['user_id', 'order_number']).drop(columns=['reorders', 'organics', 'basket_size','order_dow', 'order_hour_of_day', 'days_since_prior_order', 'days_since_first_order', 'num_orders', 'global_reorders', 'tx_purpose_weekly', 'tx_purpose_monthly', 'clusters'])
i_cols = indexed.columns

In [9]:
data.columns

Index(['user_id', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', '1% Lowfat Milk',
       '100 Calorie  Per Bag Popcorn', '100% Raw Coconut Water',
       '100% Recycled Paper Towels', '100% Whole Wheat Bread',
       ...
       'Crackers Cheddar Bunnies Snack Packs', 'days_since_first_order',
       'reorders', 'organics', 'basket_size', 'num_orders', 'global_reorders',
       'tx_purpose_weekly', 'tx_purpose_monthly', 'clusters'],
      dtype='object', length=515)

In [10]:
def get_reorders(row):
    uid = row['user_id'].astype(int)
    onum = row['order_number'].astype(int)
    if onum+1 in indexed.loc[uid].index:
        val = indexed.loc[(uid, onum+1), i_cols]
        return val
    else:
        return [None for  i in i_cols]

In [11]:
data[i_cols] = data.progress_apply(get_reorders, axis=1)

100%|█████████████████████████████████████████████████████████████████████████| 594798/594798 [24:37<00:00, 402.63it/s]

In [12]:
data = data.dropna()

In [13]:
print(data.shape)
data.head()

(584798, 515)

,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,1% Lowfat Milk,100 Calorie Per Bag Popcorn,100% Raw Coconut Water,100% Recycled Paper Towels,100% Whole Wheat Bread,...,Crackers Cheddar Bunnies Snack Packs,days_since_first_order,reorders,organics,basket_size,num_orders,global_reorders,tx_purpose_weekly,tx_purpose_monthly,clusters
63167,27,1,3,9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,83.0,0.0,0.0,0.0,2
289335,27,2,2,17,6.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.0,1.0,2.0,6.0,83.0,3.0,0.0,0.0,2
168422,27,3,3,8,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,7.0,1.0,0.0,2.0,83.0,2.0,0.0,0.0,2
495171,27,4,5,13,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,1.0,0.0,7.0,83.0,6.0,0.0,0.0,2
175636,27,5,2,15,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,17.0,2.0,0.0,2.0,83.0,1.0,0.0,0.0,2

In [14]:
cs = list(set(cols) - set(['user_id', 'clusters', 'Others']))

In [15]:
for c in cs:
    l = len(data[c].unique())
    if l > 3:
        print(c, l)

num_orders 90
order_hour_of_day 24
basket_size 112
reorders 157
global_reorders 94
order_dow 7
order_number 99
organics 35
days_since_first_order 385
days_since_prior_order 31

In [16]:
c_bins = {}
for c in cs:
    l = len(data[c].unique())
    if l > 5:
        if c == 'order_number':
            data[c], c_bins[c] = pd.qcut(data[c], 10, duplicates='drop', labels=False, retbins=True)
        else:
            data[c], c_bins[c] = pd.qcut(data[c], 5, duplicates='drop', labels=False, retbins=True)

        data[c] = data[c].map({i:f'bin_{i}' for i in range(len(data[c].unique()))})

In [17]:
c_bins

{'num_orders': array([ 13.,  47.,  59.,  74.,  96., 102.]),
 'order_hour_of_day': array([ 0.,  9., 12., 14., 17., 23.]),
 'basket_size': array([  1.,   7.,  10.,  15.,  21., 145.]),
 'reorders': array([  0.,  12.,  23.,  34.,  47., 174.]),
 'global_reorders': array([  0.,   5.,   7.,  10.,  15., 116.]),
 'order_dow': array([0., 1., 2., 3., 5., 6.]),
 'order_number': array([ 1.,  6., 12., 18., 24., 30., 37., 44., 54., 68., 99.]),
 'organics': array([ 0.,  1.,  2.,  4.,  6., 40.]),
 'days_since_first_order': array([  0.,  64., 131., 195., 266., 386.]),
 'days_since_prior_order': array([ 0.,  2.,  4.,  6.,  8., 30.])}

In [18]:
data['tx_purpose_weekly'] = data['tx_purpose_weekly'].astype(int).map({0:'No', 1:'Yes'})
data['tx_purpose_monthly'] = data['tx_purpose_monthly'].astype(int).map({0:'No', 1:'Yes'})

In [19]:
data['clusters'] = data['clusters'].apply(lambda x: f'cluster_{x}')

In [20]:
print(data.shape)
data.head()

(584798, 515)

,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,1% Lowfat Milk,100 Calorie Per Bag Popcorn,100% Raw Coconut Water,100% Recycled Paper Towels,100% Whole Wheat Bread,...,Crackers Cheddar Bunnies Snack Packs,days_since_first_order,reorders,organics,basket_size,num_orders,global_reorders,tx_purpose_weekly,tx_purpose_monthly,clusters
63167,27,bin_0,bin_2,bin_0,bin_0,0.0,0.0,0.0,0.0,0.0,...,0.0,bin_0,bin_0,bin_0,bin_0,bin_3,bin_0,No,No,cluster_2
289335,27,bin_0,bin_1,bin_3,bin_2,0.0,0.0,0.0,0.0,0.0,...,0.0,bin_0,bin_0,bin_1,bin_0,bin_3,bin_0,No,No,cluster_2
168422,27,bin_0,bin_2,bin_0,bin_0,0.0,0.0,0.0,0.0,0.0,...,0.0,bin_0,bin_0,bin_0,bin_0,bin_3,bin_0,No,No,cluster_2
495171,27,bin_0,bin_3,bin_2,bin_0,0.0,0.0,0.0,0.0,0.0,...,0.0,bin_0,bin_0,bin_0,bin_0,bin_3,bin_1,No,No,cluster_2
175636,27,bin_0,bin_1,bin_3,bin_1,0.0,0.0,0.0,0.0,0.0,...,0.0,bin_0,bin_0,bin_0,bin_0,bin_3,bin_0,No,No,cluster_2

In [21]:
group_cols = ['order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'days_since_first_order', 'num_orders', 'global_reorders', 'tx_purpose_weekly', 'tx_purpose_monthly', 'clusters']
drop_cols = ['user_id' ]

In [22]:
grouped = data.drop(columns=drop_cols).groupby(group_cols).mean().progress_apply(lambda x: x*100/sum(x), axis=1)

100%|████████████████████████████████████████████████████████████████████████| 257505/257505 [01:11<00:00, 3590.32it/s]

In [23]:
print(grouped.shape)
grouped.head()

(257505, 501)

                                                                                                                                                                   1% Lowfat Milk  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0              0.0
                                                                                                                                                       cluster_1              0.0
                                                                                                                                                       cluster_11             0.0
                                                                                                                                                       cluster_3              0.0
                                                                                                                                                       cluster_4              0.0

                                                                                                                                                                   100 Calorie  Per Bag Popcorn  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                            0.0
                                                                                                                                                       cluster_1                            0.0
                                                                                                                                                       cluster_11                           0.0
                                                                                                                                                       cluster_3                            0.0
                                                                                                                                                       cluster_4                            0.0

                                                                                                                                                                   100% Raw Coconut Water  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                      0.0
                                                                                                                                                       cluster_1                      0.0
                                                                                                                                                       cluster_11                     0.0
                                                                                                                                                       cluster_3                      0.0
                                                                                                                                                       cluster_4                      0.0

                                                                                                                                                                   100% Recycled Paper Towels  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                          0.0
                                                                                                                                                       cluster_1                          0.0
                                                                                                                                                       cluster_11                         0.0
                                                                                                                                                       cluster_3                          0.0
                                                                                                                                                       cluster_4                          0.0

                                                                                                                                                                   100% Whole Wheat Bread  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                      0.0
                                                                                                                                                       cluster_1                      0.0
                                                                                                                                                       cluster_11                     0.0
                                                                                                                                                       cluster_3                      0.0
                                                                                                                                                       cluster_4                      0.0

                                                                                                                                                                   2% Reduced Fat DHA Omega-3 Reduced Fat Milk  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                                           0.0
                                                                                                                                                       cluster_1                                           0.0
                                                                                                                                                       cluster_11                                          0.0
                                                                                                                                                       cluster_3                                           0.0
                                                                                                                                                       cluster_4                                           0.0

                                                                                                                                                                   2% Reduced Fat Milk  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                   0.0
                                                                                                                                                       cluster_1                   0.0
                                                                                                                                                       cluster_11                  0.0
                                                                                                                                                       cluster_3                   0.0
                                                                                                                                                       cluster_4                   0.0

                                                                                                                                                                   2% Reduced Fat Organic Milk  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                      0.000000
                                                                                                                                                       cluster_1                      0.000000
                                                                                                                                                       cluster_11                     1.923077
                                                                                                                                                       cluster_3                      0.000000
                                                                                                                                                       cluster_4                      0.000000

                                                                                                                                                                   Aged White Cheddar Baked Rice & Corn Puffs Gluten Free Lunch Packs  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                                            0.000000
                                                                                                                                                       cluster_1                                            0.000000
                                                                                                                                                       cluster_11                                           0.000000
                                                                                                                                                       cluster_3                                            2.083333
                                                                                                                                                       cluster_4                                            0.000000

                                                                                                                                                                   Air Chilled Breaded Chicken Breast Nuggets  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                                          0.0
                                                                                                                                                       cluster_1                                          0.0
                                                                                                                                                       cluster_11                                         0.0
                                                                                                                                                       cluster_3                                          0.0
                                                                                                                                                       cluster_4                                          0.0

                                                                                                                                                                   ...  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters    ...
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0   ...
                                                                                                                                                       cluster_1   ...
                                                                                                                                                       cluster_11  ...
                                                                                                                                                       cluster_3   ...
                                                                                                                                                       cluster_4   ...

                                                                                                                                                                   YoBaby Blueberry Apple Yogurt  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                             0.0
                                                                                                                                                       cluster_1                             0.0
                                                                                                                                                       cluster_11                            0.0
                                                                                                                                                       cluster_3                             0.0
                                                                                                                                                       cluster_4                             0.0

                                                                                                                                                                   YoBaby Peach Pear Yogurt  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                        0.0
                                                                                                                                                       cluster_1                        0.0
                                                                                                                                                       cluster_11                       0.0
                                                                                                                                                       cluster_3                        0.0
                                                                                                                                                       cluster_4                        0.0

                                                                                                                                                                   YoKids Blueberry & Strawberry/Vanilla Yogurt  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                                            0.0
                                                                                                                                                       cluster_1                                            0.0
                                                                                                                                                       cluster_11                                           0.0
                                                                                                                                                       cluster_3                                            0.0
                                                                                                                                                       cluster_4                                            0.0

                                                                                                                                                                   YoKids Squeeze! Organic Strawberry Flavor Yogurt  \
order_number order_dow order_hour_of_day days_since_prior_order days_since_first_order num_orders global_reorders tx_purpose_weekly tx_purpose_monthly clusters
bin_0        bin_0     bin_0             bin_0                  bin_0                  bin_0      bin_0           No                No                 cluster_0                                                0.0
                                                                                                                                                       cluster_1                                                0.0
                                                                                                                                                       cluster_11                                               0.0
                                                                                                                                                       cluster_3                                                0.0
                                                                                                                                                       cluster_4                                                0.0


In [24]:
grouped.index.names

FrozenList(['order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'days_since_first_order', 'num_orders', 'global_reorders', 'tx_purpose_weekly', 'tx_purpose_monthly', 'clusters'])

In [25]:
g = grouped.iloc[100]
g[g > 0].index

Index(['100% Whole Wheat Bread', '2% Reduced Fat DHA Omega-3 Reduced Fat Milk',
       'Apple Honeycrisp Organic', 'Asparagus', 'Bag of Organic Bananas',
       'Banana', 'Chicken & Maple Breakfast Sausage', 'Crushed Tomatoes',
       'Electrolyte Enhanced Water',
       'Ezekiel 4:9 Bread Organic Sprouted Whole Grain', 'Fat Free Milk',
       'Fresh Cauliflower',
       'Gogo Squeez Organic Apple Strawberry Applesauce on the Go',
       'Hass Avocados', 'Kidz All Natural Baked Chicken Nuggets', 'Limes',
       'Marinara Sauce', 'Organic 1% Low Fat Milk', 'Organic AppleApple',
       'Organic Avocado', 'Organic Blueberries',
       'Organic Boneless Skinless Chicken Breast', 'Organic Braeburn Apple',
       'Organic Carrot Bunch', 'Organic Creamy Peanut Butter',
       'Organic D'Anjou Pears', 'Organic Extra Large Grade AA Brown Eggs',
       'Organic Frozen Mango Chunks', 'Organic Gala Apples',
       'Organic Grape Tomatoes', 'Organic Half & Half', 'Organic Hass Avocado',
       'Organic Honey Sweet Whole Wheat Bread',
       'Organic Lactose Free Whole Milk',
       'Organic Large Extra Fancy Fuji Apple', 'Organic Mango',
       'Organic Medium Salsa', 'Organic Original Hommus', 'Organic Quick Oats',
       'Organic Raspberries', 'Organic Red Onion', 'Organic Red Radish, Bunch',
       'Organic Reduced Fat Milk', 'Organic Salted Butter',
       'Organic Shredded Mozzarella', 'Organic Small Bunch Celery',
       'Organic Strawberries', 'Organic Sugar Snap Peas',
       'Organic Unsweetened Almond Milk',
       'Organic Unsweetened Vanilla Almond Milk', 'Organic Yellow Squash',
       'Organic Zucchini', 'Others', 'Pineapple Chunks', 'Seedless Red Grapes',
       'Sliced Black Olives', 'Small Hass Avocado',
       'Sparkling Water Grapefruit', 'Total 0% Nonfat Greek Yogurt',
       'Total 2% All Natural Greek Strained Yogurt with Honey',
       'Uncured Hickory Smoked Sunday Bacon', 'Watermelon Chunks',
       'White Corn', 'Wild Berry Smoothie', 'YoBaby Peach Pear Yogurt'],
      dtype='object')

In [26]:
## NOTE TO HALA: One good thing that differentiates what we are doing is that we are not taking in the user ID, 
## so we are more generic than what is on kaggle, this also applies for the instacart model (notebook 5)
## Also it is best to focus title to "Sequence models" instad of Seq2Seq models, since this new model is seq noo